### ISSUE TITLE
Finish template files

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/ccn-template#2]
- [x] add tests, make sure github actions run -- #6 
- [x] add deploy action -- #21 
- [x] make sure documentation builds -- #8 
- [x] connect to readthedocs -- #8 
- [x] test notebook with mkdocs-gallery -- #1 
- [x] add some basic code for tests, linters to check -- #6 adds some for this, and we'll add others as needed to demonstrate points (e.g., here's a unit test)
- [x] test `tox` runs -- #6 
- [x] test that package can be built and installed from test.pypi.org -- #21

**Comment by billbrod** [comment]
Closing issue, as all the separate tasks have their own PRs / issues
